var nodemailer = require('nodemailer');

var transport = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    auth: {
        user: "diegomombelli03@gmail.com", //generated by Mailtrap
        pass: "10062003Diego" //generated by Mailtrap
    }
});

var mailOptions = {
    from: 'diegomombelli03@gmail.com',
    to: 'diegomombelli@outlook.com',
    subject: 'Nice Nodemailer test',
    text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
    html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer'
};

transport.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message sent: %s', info.messageId);
});